language: python
python:
  - "3.6"
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt


before_script:
  - python server.py &

# command to run tests
script:
   
  - py.test
